
sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
    
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

branches:
  only:
    - master
    - sse

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - jest
  
