
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0

os: linux 

files:
  - source: /
    destination: /var/www/html/

permissions:
   - object: /var/www/html
     pattern: "**"
     owner: node
     group: node
     mode: 755
     type:
       - file

hooks:
  BeforeInstall:
    - location: ./scripts/installnode.sh
      runas: root
    - location: ./scripts/startnode.sh
      runas: root

  AfterInstall:
    - location:  ./scripts/restartnode.sh   
      runas: root
# During the ApplicationStart deployment lifecycle event, run the commands 
#   in the script specified in "location".
  ApplicationStart:
    - location:     
      timeout: 
      runas:
    - location: 
      timeout:
      runas:
# During the ValidateService deployment lifecycle event, run the commands 
#   in the script specified in "location".
  ValidateService:
    - location:     
      timeout: 
      runas:
    - location: 
      timeout:
      runas: